language: node_js
node_js:
    - "5.12.0"
install:
    - npm install -g typings
    - npm install -g webpack
    - npm install
    - typings install
    - npm run build
after_script:
    - sh ./.cf.sh userstat